# Trigger additional actions after a GitHub Release has been created
name: Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: test
        run: src\build.ps1
