name: Build

on:
  push:
    paths:
      - '0install-dotnet/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '0install-dotnet/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:

  build:
    strategy: 
      matrix: 
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        vs-prerelease: true
        msbuild-architecture: x64

    - name: restore
      run: msbuild -t:restore

    - name: Build
      run: msbuild src\ZeroInstall.sln -p:Configuration=${{ matrix.configuration }}
